### ISSUE TITLE
rollup.config.js missing external flag

### ISSUE THREAD

**Issue by juliankrieger** [screepers/screeps-typescript-starter#105]
I had problems using the ts starter because of it not being able to import libraries via 'require' until I added 
```
external: [
    "fs"
  ],
```

to my rollup.config.js. This fixed the problem on my side. Should I consider issueing a pull request?

**Comment by Jomik** [comment]
Why are you using `require` in TypeScript?

**Comment by kotarou** [comment]
You should not be using require when rollup is used. Import statements can be used for the same functionality.
