### ISSUE TITLE
needed to remove "screeps-server-mockup": "^1.4.3" from packages.json and install python2

### ISSUE THREAD

**Issue by roswell67** [screepers/screeps-typescript-starter#108]
Things didn't work at all with yarn or npm install, needed to do the following steps to work:

1) Install Python2 and make sure it's included in PATH
2) remove "screeps-server-mockup": "^1.4.3" from packages.json

For anyone out there, please do the above steps to work and i hope someone can update the readme file.

**Comment by Jomik** [comment]
Why did you need to remove `screeps-server-mockup` ? It should be usable.
And which plugin requires python? I don't recall needing python, nor do I have it installed in my `PATH`.
Python is mentioned in #107 as well.

**Comment by BCNelson** [comment]
screeps-server-mockup has been deprecated and has security vulnerabilities

**Comment by xtagon** [comment]
If it has been deprecated, what is the recommended alternative for running integration tests?

**Comment by kotarou** [comment]
While it is noted as deprecated, it still works. It is however, annoying to get running, and propably should not be included in a starter package as a result. See Issue #117. Closing this for consolodation.

**Comment by djD-REK** [comment]
@xtagon  There is an updated version available, see the discussion in #124  @kotarou  😄
