### ISSUE TITLE
🙏 Thank you for this project!

### ISSUE THREAD

**Issue by djD-REK** [screepers/screeps-typescript-starter#134]
Just wanted to say thanks! 🙏

I was running into issues with the .lookForAtArea "look results" object not being a proper RoomPosition object, and I decided I should switch my codebase to TypeScript.

You made it so easy!

I'd already struggled through installing the screeps constants and the eslint-screeps-plugin, but I hadn't figured out how to test my code yet.  You made that super easy too!

Thanks so much.

**Comment by pyrodogg** [comment]
Thanks!

There's a great community in the #typescript channel on the Screeps Slack, come join. https://chat.screeps.com/
