### ISSUE TITLE
gulpfile.js is removed during gulp build

### ISSUE THREAD

**Issue by rickpelletier** [screepers/screeps-typescript-starter#14]
Hi, my gulpfile.js keeps getting deleted when I do the `npm run deploy` (or `gulp build`):

Console log of a full wipe and reclone:

https://files.slack.com/files-pri/T0HJCPP9T-F1W1334CR/full_wipe_and_reclone.txt

**Comment by valerian** [comment]
That's very strange, it seems to be related to a path issue with the `dist` folder, it's as if it was ignoring it and putting all at the root folder!
I made a branch named `osx-gulpfile-issue` to try fixing this issue, can you try with it instead of `master`, and tell me the result?
Also in both cases, can you show me the result of `ls -l` both in `sim` and `sim/dist`?
If you are on the screeps slack, what is your nickname there?

**Comment by rickpelletier** [comment]
@dushinto on Slack

MacBook-Pro:sim richard$ git status
On branch osx-gulpfile-issue
Your branch is up-to-date with 'screepers/osx-gulpfile-issue'.
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

```
deleted:    gulpfile.js
```

Untracked files:
  (use "git add <file>..." to include in what will be committed)

```
.idea/
components.creeps.creepAction.js
components.creeps.creepManager.js
components.creeps.harvester.js
components.rooms.roomManager.js
components.sources.sourceManager.js
components.spawns.spawnManager.js
config.config.js
main.js
shared.memoryManager.js
```

no changes added to commit (use "git add" and/or "git commit -a")
MacBook-Pro:sim richard$ ls -l
total 136
-rw-r--r--   1 richard  staff  4671 Jul 28 09:12 README.md
-rw-r--r--@  1 richard  staff   845 Jul 28 09:27 components.creeps.creepAction.js
-rw-r--r--@  1 richard  staff  2117 Jul 28 09:27 components.creeps.creepManager.js
-rw-r--r--@  1 richard  staff  1296 Jul 28 09:27 components.creeps.harvester.js
-rw-r--r--@  1 richard  staff   613 Jul 28 09:27 components.rooms.roomManager.js
-rw-r--r--@  1 richard  staff   507 Jul 28 09:27 components.sources.sourceManager.js
-rw-r--r--@  1 richard  staff   654 Jul 28 09:27 components.spawns.spawnManager.js
-rw-r--r--@  1 richard  staff   129 Jul 28 09:27 config.config.js
-rw-r--r--   1 richard  staff    85 Jul 28 09:12 config.example.json
-rw-r--r--   1 richard  staff    91 Jul 28 09:13 config.json
drwxr-xr-x   4 richard  staff   136 Jul 28 09:27 dist
drwxr-xr-x   4 richard  staff   136 Jul 28 09:12 libs
-rw-r--r--@  1 richard  staff   786 Jul 28 09:27 main.js
drwxr-xr-x  19 richard  staff   646 Jul 28 09:27 node_modules
-rw-r--r--   1 richard  staff   753 Jul 28 09:12 package.json
-rw-r--r--@  1 richard  staff    99 Jul 28 09:27 shared.memoryManager.js
drwxr-xr-x   6 richard  staff   204 Jul 28 09:17 src
-rw-r--r--   1 richard  staff   820 Jul 28 09:12 tsconfig.json
-rw-r--r--   1 richard  staff   290 Jul 28 09:12 tslint.json
drwxr-xr-x   4 richard  staff   136 Jul 28 09:27 typings
-rw-r--r--   1 richard  staff   235 Jul 28 09:12 typings.json
MacBook-Pro:sim richard$ ls -l dist
total 0
drwxr-xr-x  11 richard  staff  374 Jul 28 09:27 flat
drwxr-xr-x   6 richard  staff  204 Jul 28 09:27 src
MacBook-Pro:sim richard$ ls -l dist/flat
total 72
-rw-r--r--  1 richard  staff   845 Jul 28 09:27 components.creeps.creepAction.js
-rw-r--r--  1 richard  staff  2117 Jul 28 09:27 components.creeps.creepManager.js
-rw-r--r--  1 richard  staff  1296 Jul 28 09:27 components.creeps.harvester.js
-rw-r--r--  1 richard  staff   613 Jul 28 09:27 components.rooms.roomManager.js
-rw-r--r--  1 richard  staff   507 Jul 28 09:27 components.sources.sourceManager.js
-rw-r--r--  1 richard  staff   654 Jul 28 09:27 components.spawns.spawnManager.js
-rw-r--r--  1 richard  staff   129 Jul 28 09:27 config.config.js
-rw-r--r--  1 richard  staff   786 Jul 28 09:27 main.js
-rw-r--r--  1 richard  staff    99 Jul 28 09:27 shared.memoryManager.js
MacBook-Pro:sim richard$

**Comment by valerian** [comment]
So you have the files both in `sim` and in `sim/dist/flat` for some reason ...
It's a bit hard to investigate if I don't have access to a mac, it could be many things! Maybe it's the upload that messes up? can you try to just do `gulp flatten` instead of `gulp build`?

**Comment by valerian** [comment]
so after some testing, the issue seems to only happen when `.pipe(gulpScreepsUpload(config.email, config.password, config.branch, 0))` is run.

The files created at the root have this special osx attribute `com.apple.quarantine` which is related to malware protection.
Something really fishy is happening there, and I can't really investigate it without a mac.

**Comment by valerian** [comment]
branch `osx-gulpfile-issue` deleted since it did nothing

**Comment by valerian** [comment]
problem solved: rickpelletier was running the project directly within a screeps branch folder synced through steam ...
