### ISSUE TITLE
Why do we run unit/integration mocha tests through Rollup?

### ISSUE THREAD

**Issue by brisberg** [screepers/screeps-typescript-starter#143]
This might be a philosophical question but why are we using `Rollup` to bundle the project source with the test files before executing them with `mocha`?

Is it to be able to run mocha of `TypeScript` files?

If so, I feel there is a much easier way to do it that requires much less duplicate configuration.

We can use [`ts-node`](https://www.npmjs.com/package/ts-node) to transpile sources on the fly. Optionally we can add [`tsconfig-paths`](https://www.npmjs.com/package/tsconfig-paths) to get `ts-node` to respect the `baseUrl` typescript compiler option.

Documentation source: https://github.com/TypeStrong/ts-node#loading-tsconfigjson

This is not only much faster, as we don't need to do a full rollup bundle first, it still preserves breakpoints and error reporting through the source maps.

In fact, `ts-node` is already an unused dependency of this project! I propose using `ts-node` to simplify unit testing configuration.

See: #144

**Comment by pyrodogg** [comment]
Thanks. This seems like a reasonable simplification of the included testing scripts. I don't see any strong need to require bundling in unit testing. If one wanted to verify that bundling is happening correctly that would be a separate concern from unit testing logic.

**Comment by brisberg** [comment]
Cheers
