### ISSUE TITLE
Remove types.d.ts

### ISSUE THREAD

**Issue by pyrodogg** [screepers/screeps-typescript-starter#147]
Typescript provides the ability to define types for imported javascript packages using `.d.ts` files. Defining custom typse for screeps in this way is a bit odd though.  We're never importing the game api to work with, it just _exists_ in the global runtime by default. 

Loose `.d.ts` files can also easily turn into a "dumping ground" for global type definitions which isn't best practice.

Recent changes to testing scripts in #144 don't load `src/types.d.ts` [by default](https://github.com/TypeStrong/ts-node#help-my-types-are-missing), causing tests to fail (#146) if they rely on types in this file. More could be done to work around this and load the file, but I think this is the final nudge to rework the example types and remove [types.d.ts](src/types.d.ts).

* [ ] Review how much boilerplate type examples are really needed for demonstrating the extension of game interfaces
* [ ] Relocate updated boilerplate types to `.ts` files

**Comment by Josef37** [comment]
Sorry, if these questions are too basic or off-topic, I'm just getting to know TS with the help of this project. 😅

1. Would you recommend importing types from `.ts` files when they are used (and not using `.d.ts` files at all)?
Or how would you recommend to set up typings in such a project?

2. I don't really know how to handle these globals that just _exist_... 
You have to extend them, if you want to use `Memory` at all.
So (for now) I moved my type declarations to `./typings/global/index.d.ts` and edited `tsconfig.test.json` like so:
```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "module": "CommonJS",
    "typeRoots": [
      "./node_modules/@types",
      "./typings"
    ]
  }
}
```

3. What is your preferred strategy for mocking these globals? Is the example in `main.test.ts` the only viable option?

**Comment by pyrodogg** [comment]
You can handle both cases, locally scoped types that need to be explicitly exported and imported to be used, and globally available types in `.ts` modules. The recommendation to put types in `.ts` files doesn't strictly impose a limit on using global types.

Again, `.d.ts` files and compiler directives like `typeRoots` are really meant for telling the compiler where to find types for 3rd party dependencies. not your own types.

If you want to define a type to be globally available (ex. adding attributes to `Memory`) put them in a `global` block within a `.ts` module.

```Typescript
// main.ts
import { ErrorMapper } from "utils/ErrorMapper";

declare global {
  // Types defined in a global block are available globally
  interface Memory {
   foo: string;
  }
}

export loop = ...
```

This Memory interface declaration would be merged with the ones coming from `@types/screeps`.

**Comment by Josef37** [comment]
Oh... Great to know the purpose of `.d.ts` files finally 😅 

When runninng an unit test, where the tested file uses something from `Memory`, `main.ts` would not be loaded and I get an error. Should this file import `main.ts` then?
