### ISSUE TITLE
Unable to run unit tests (Types not found, neither mine nor Screeps)

### ISSUE THREAD

**Issue by JPCSoares** [screepers/screeps-typescript-starter#148]
I seem unable to run any unit-test at all:

Tests that rely on change I made to types.d.ts seem to fall under #147, that's understandable, the types.d.ts feels like a crutch anyway.

But I have a test that is a simple as:

somefile.ts:
```
export function CostPerPart(part: BodyPartConstant): number {
  switch (part) {
    case WORK:
      return 100;
  }
}
```

somefile.test.ts:
```
describe("part cost", () => {
  it("part costs are correct", () => {
    const parts = CostPerPart(WORK);
    assert.equal(parts, 100);
  });
});
```

which fails with: 
> ReferenceError: WORK is not defined

Unfortunately I don't how to solve this, was hoping someone could give me a hand here.
Did try to mess around the configs to get it to work but no success.

**Comment by pyrodogg** [comment]
Types are just types, they don't exist at runtime. What you need is to actually mock the constants provided by the game. There really isn't anything documented in this starter project for it. 

You could take a look at screeps-jest https://github.com/eduter/screeps-jest/blob/master/src/setupGlobals.ts or screeps-typescript-jest-starter for more on unit testing.

**Comment by LokiSharp** [comment]
I assign all constant in setup-node.ts that I can use their in unit test

 https://github.com/LokiSharp/ScreepsScript/blob/master/test/setup-node.ts
