### ISSUE TITLE
Have the gulpfile block the script from running if it's run from within the Steam directory.

### ISSUE THREAD

**Issue by resir014** [screepers/screeps-typescript-starter#21]
As per #14 and #18, there would be some cases where running the script from inside Steam's synced folder would case the gulpfile to shit the bed. We should have the gulp tasks detect if it's being run from the Steam directory, and block it from running.

(ping @valerian)

**Comment by valerian** [comment]
I won't be available to do that until Wednesday at least

**Comment by resir014** [comment]
Workaround to this issue available on #30. Closing for now.
