### ISSUE TITLE
Magenta gulp log entries invisible in Powershell

### ISSUE THREAD

**Issue by TimoStaudinger** [screepers/screeps-typescript-starter#25]
In the default setting of Powershell, `gutils.log` entries that are colored in magenta using `gutils.colors.magenta()` are practically invisible as the font color nearly matches the background color.

This is a known issue with the library `chalk` that is used internally by `gulp-utils`: https://github.com/chalk/chalk/issues/2

To resolve this, I suggest to change the output color from magenta to cyan on all instances.

Any thoughts on this?

![image](https://cloud.githubusercontent.com/assets/5621996/18999860/b053e260-870d-11e6-998c-58bb03e6b3b9.png)

**Comment by resir014** [comment]
Unfortunately, those log outputs are default by Gulp, and until now there's no way to change them. They're planning to add this functionality at gulpjs/gulp-cli#63, but they haven't gone through with it yet.

I suggest changing the base color scheme of your PowerShell window, or using an alternate console like [ConEmu](https://conemu.github.io/) or [Cmder](http://cmder.net/).
