### ISSUE TITLE
Upgrade to Webpack 2

### ISSUE THREAD

**Issue by resir014** [screepers/screeps-typescript-starter#33]
Now that [Webpack 2 has reached stable](https://medium.com/webpack/webpack-2-2-the-final-release-76c3d43bf144), we'll have to eventually convert the code over to Webpack 2. I'm putting this issue up here as a reminder to start working on it by the end of this week.

**Comment by bastianh** [comment]
If possible it should also use webpacks watch. It compiles about 30x faster on my laptop if it can use webpacks cache. 
Because of that I'm now using webpack without gulp in the moment.

**Comment by resir014** [comment]
@bastianh I'll look into it. Right now the main priority is to get the build scripts working with Webpack 2.

**Comment by resir014** [comment]
Starter kit now runs on Webpack 2 as of #35. Transition to Webpack's watch will be tracked on #36.
