### ISSUE TITLE
Why is is the starter full of `let` uses, when project linting rules prefer `const`?

### ISSUE THREAD

**Issue by bryanbecker** [screepers/screeps-typescript-starter#46]
It's frustrating that straight out of the box the project is littered with errors (warnings, really).

Should we change the `let`s to `const`s per the linter's recommendation?

Should we change the default linting to not worry about it?

Something to think about:  I've seen it mentioned on slack that `const` is slower in CPU terms.  No idea if this is true or just a slack old-wives tale, but something to consider

**Comment by resir014** [comment]
Yeah sorry about that, TSLint 5 just updated a lof of their rules,
especially re: `const`. I'll update the starter kit to make it
TSLint5-compliant when I got access to it.

**Comment by resir014** [comment]
This should be fixed now. Closing.
