### ISSUE TITLE
Remove testing framework from project

### ISSUE THREAD

**Issue by resir014** [screepers/screeps-typescript-starter#52]
See #44.

Since the Webpack update broke the testing functionality on the starter pack, we might have to rewrite the entire testing framework. I'm looking into using [`magical-mock`](https://www.npmjs.com/package/magical-mock). If it works well, we could use it.

**Comment by Triavanicus** [comment]
All I did was change the package.json to use mocha directly, and it seems to work fine.
`"test": "mocha",`

**Comment by resir014** [comment]
The common consensus among the `#typescript` people has been to remove the testing codes altogether. Updating this issue to reflect that.
