### ISSUE TITLE
trying to follow installation instructions

### ISSUE THREAD

**Issue by RodionPronin** [screepers/screeps-typescript-starter#65]
And keep getting this.
Any help would be appreciated

![image](https://user-images.githubusercontent.com/22927581/27997850-beb4b3f8-64ce-11e7-8ff5-414094a815f0.png)

**Comment by resir014** [comment]
Looks like `webpack-sources` isn't installed. Try re-running `npm install`.

**Comment by resir014** [comment]
Since this has no response for more than a month, I'm closing this as answered. Feel free to create a new issue if you still ran into the same problem.
