### ISSUE TITLE
[v3.0] Support multiple destinations for uploading

### ISSUE THREAD

**Issue by dmarcuse** [screepers/screeps-typescript-starter#75]
Right now you can only specify a single destination for the bundled code. We should support pushing to different branches and/or servers.

The way I'd like to implement this would be to use environment variables, set in the `scripts` block in `package.json` (e.g. `SCREEPS_DESTINATION=... rollup -c` or similar) which can then be read in the rollup config using `process.env`. If [this](https://github.com/Arcath/rollup-plugin-screeps/pull/1) gets merged it should be very easy to change it so that `screeps.json` contains a map of names to destination configs, which then have their own script in `package.json` to set the appropriate variable.

**Comment by ezolenko** [comment]
You can look at `getConfigName` [here ](https://github.com/ezolenko/rollup-plugin-screeps-upload/blob/master/src/rollup-plugin-screeps-upload.ts) for example of how to add cmd line args to rollup. Add that to your plugin and do `rollup -c --screeps <config file name>` in npm scripts.

**Comment by dmarcuse** [comment]
That would also work fine, and probably would be more user-friendly than environment variables.

**Comment by dmarcuse** [comment]
You can now use `--dest` to specify which destination to upload to. Omitting the argument will perform a dry run, which can be used for local directories via symlinks.
