### ISSUE TITLE
Implement token-based auth system

### ISSUE THREAD

**Issue by resir014** [screepers/screeps-typescript-starter#80]
Screeps has recently introduced a [token-based auth system](http://blog.screeps.com/2017/12/auth-tokens/), and the old authentication system will be deprecated by 01 February 2018. We should start look into implementing the new auth system and deprecate the old one.

This task will be on hold until https://github.com/Arcath/rollup-plugin-screeps/issues/2 is resolved and the new auth system is implemented in `rollup-plugin-screeps`.

**Comment by Arcath** [comment]
`rollup-plugin-screeps` should support tokens now.
