### ISSUE TITLE
Indexing via Type

### ISSUE THREAD

**Issue by MDLeide** [screepers/screeps-typescript-starter#82]
When I try to build a project I get several of the following errors:

`Build: Type 'T' cannot be used to index type 'FindTypes'.`
 from
`type FilterFunction<T extends FindConstant> = (object: FindTypes[T]) => boolean;`
It looks like it's trying to use the constant associated with the Type... but I'm not really sure. Any ideas?

**Comment by resir014** [comment]
@MDLeide This seems to be an issue related to https://github.com/screepers/typed-screeps. Could you re-create the issue there?

**Comment by MDLeide** [comment]
Sure can. Didn't realize the projects were independent.
