### ISSUE TITLE
Rate limit information on script upload

### ISSUE THREAD

**Issue by piotrgajow** [screepers/screeps-typescript-starter#83]
Using Screeps endpoints is limited as described in [documentation](http://docs.screeps.com/auth-tokens.html#Rate-Limiting).

It would be nice to be informed if I am approaching the limit after executing API call.

I could work on the implementation if someone could give me some tip where to start.

**Comment by Arcath** [comment]
I have a post about the rate limits for code pushing on the forums. https://screeps.com/forum/topic/2052/auth-tokens/55

**Comment by piotrgajow** [comment]
So, do I understand it corretly, that the limit is intended only for automated tools, thus it should be removed from the rollup, and function proposed by me won't be needed?

**Comment by Arcath** [comment]
You can now manually set your token to unlimited as described here http://docs.screeps.com/auth-tokens.html#Turning-rate-limiting-off

I'm going to close this now as it's not an issue with the typescript starter.
