### ISSUE TITLE
[RFC] Auto-formatting of code with Prettier

### ISSUE THREAD

**Issue by resir014** [screepers/screeps-typescript-starter#85]
[Prettier](https://prettier.io/) is an awesome tool which help you automatically format your code. It supports integration with popular linting tools like ESLint and TSLint, as well as really good integration with editors (like VS Code), with support for formatting after save.

Right now I could include it by either:

* including an opinionated Prettier config on the codebase, or
* creating a new doc article in the [Cookbook](https://screepers.gitbooks.io/screeps-typescript-starter/in-depth/cookbook.html) section with a guide on including Prettier.

I'm more gravitated towards doing the latter, so to not complicate the default setup even further. I'll write down a quick guide on including Prettier which should be finished by the end of next week.

**Comment by dmarcuse** [comment]
One of the things I like about the current state of the starter kit is that it's pretty minimal and easy to understand how everything works. I'm not opposed to adding prettier as long as it's clearly explained what it does. Usually I'm not a fan of forcing style guides, but TSLint already does that and it's easy to change.
