### ISSUE TITLE
Reports `cannot find module "source-map"` in VSCode, but compiles normally

### ISSUE THREAD

**Issue by cai-lw** [screepers/screeps-typescript-starter#88]
Also `tsc` reported the same error and failed. But `rollup` succeeded.

**Comment by cai-lw** [comment]
https://github.com/Microsoft/TypeScript/issues/10346

Adding
```json
"moduleResolution": "node"
```
to `tsconfig.js` solves the problem.

**Comment by DavidTriphon** [comment]
This worked for me. Thank you for the fix suggestion.

**Comment by dmarcuse** [comment]
Fixed in #89
